name:         glutils
version:      0.0.1
author:       Herman Bergwerf <hermanbergwerf@gmail.com>
description:  Simple WebGL utility library
homepage:     https://github.com/bergwerf/glutils
environment:
  sdk:        '>=2.0.0 <3.0.0'
dependencies:
  vector_math: ^2.0.8
