name:         glutils
version:      0.0.0
author:       Herman Bergwerf <hermanbergwerf@gmail.com>
description:  Simple WebGL utility library
homepage:     https://github.com/hermanbergwerf/glutils
environment:
  sdk:        '>=1.8.0 <2.0.0'
dependencies:
  vector_math: ^2.0.4
